language: go
sudo: required
services:
  - docker
script:
  - ./build.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push panux/dlserver panux/worker panux/buildmanager;
    fi
