language: go
sudo: required
services:
  - docker
script:
  - ./build.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    for i in dlserver worker buildmanager; do
    docker push panux/$i
    done
    fi
