
# Makefile autogenerated by PackageGenerator.GenFullMakefile (see godoc.org/github.com/panux/builder/pkgen)
# DO NOT EDIT

# Package Information
# -------------------
# Packages: bison bison-doc bison-man
# Version: 3.0.4-0
# Arch (host, build): x86_64, x86_64
# Builder: bootstrap
# Build Dependencies: perl m4

all: gentars

# Section autogenerated by PackageGenerator.InitializeVars (see godoc.org/github.com/panux/builder/pkgen)
# DO NOT EDIT
SRCTAR = src.tar
TAROUT = tars
HOSTARCH = x86_64
BUILDARCH = x86_64

# Section autogenerated by PackageGenerator.GenMake (see godoc.org/github.com/panux/builder/pkgen)
# DO NOT EDIT
gentars: $(TAROUT)/bison.tar.gz $(TAROUT)/bison-doc.tar.gz $(TAROUT)/bison-man.tar.gz
pkginfos: out/bison/.pkginfo out/bison-doc/.pkginfo out/bison-man/.pkginfo
src/%.pkginfo: untarsource
untarsource: $(SRCTAR) src
	tar -xf $< -C src
.PHONY: gentars pkginfos
# Directory structure rules
src:
	@echo MKDIR src
	@mkdir src
out:
	@echo MKDIR out
	@mkdir out
$(TAROUT):
	@echo MKDIR $(TAROUT)
	@mkdir $(TAROUT)
out/bison: out
	@echo MKDIR out/bison
	@mkdir out/bison
out/bison-doc: out
	@echo MKDIR out/bison-doc
	@mkdir out/bison-doc
out/bison-man: out
	@echo MKDIR out/bison-man
	@mkdir out/bison-man
out/bison/.pkginfo: src/bison.pkginfo out/bison
	@echo PKGINFO bison
	@cp -f $< $@
$(TAROUT)/bison.tar.gz: script $(TAROUT)
	@echo TAR bison.tar.gz
	@tar -cf $@ -C out/bison .
out/bison-doc/.pkginfo: src/bison-doc.pkginfo out/bison-doc
	@echo PKGINFO bison-doc
	@cp -f $< $@
$(TAROUT)/bison-doc.tar.gz: script $(TAROUT)
	@echo TAR bison-doc.tar.gz
	@tar -cf $@ -C out/bison-doc .
out/bison-man/.pkginfo: src/bison-man.pkginfo out/bison-man
	@echo PKGINFO bison-man
	@cp -f $< $@
$(TAROUT)/bison-man.tar.gz: script $(TAROUT)
	@echo TAR bison-man.tar.gz
	@tar -cf $@ -C out/bison-man .
.ONESHELL:
script: untarsource pkginfos
	set -ex
	tar -xf src/bison-3.0.4.tar.xz
	mv bison-3.0.4 bison
	(cd bison && ./configure --build x86_64-pc-linux-musl --host x86_64-pc-linux-musl --prefix=/usr --sysconfdir=/etc --mandir=/usr/share/man --localstatedir=/var --datadir=/usr/share --infodir=/usr/share/info)
	$(MAKE) -C bison
	$(MAKE) -C bison DESTDIR=$(shell pwd)/out/bison install
	mkdir -p out/bison-man/usr/share
	mv out/bison/usr/share/man out/bison-man/usr/share
	mkdir -p out/bison-doc/usr/share
	mv out/bison/usr/share/doc out/bison-doc/usr/share
	mkdir -p out/bison-doc/usr/share
	mv out/bison/usr/share/info out/bison-doc/usr/share
	
