FROM alpine:3.6
RUN apk --no-cache add make git gcc libc-dev ccache
COPY worker /usr/bin/worker
COPY cmd/worker/bootstrap.sh /root/bootstrap.sh
ENV PATH="/usr/lib/ccache/bin:${PATH}"
ENV CCACHE_DIR=/ccache
ENTRYPOINT ["worker"]
