FROM golang:alpine as workerbuilder
WORKDIR /root
RUN apk --no-cache add make git gcc libc-dev
COPY . /go/src/github.com/panux/builder
RUN CGO_ENABLED=0 go build -o worker github.com/panux/builder/cmd/worker

FROM alpine:3.7
RUN apk --no-cache add make git gcc libc-dev
COPY --from=workerbuilder /root/worker /usr/bin/worker
COPY cmd/worker/bootstrap.sh /root/bootstrap.sh
ENTRYPOINT ["worker"]
