---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: buildmanager
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: buildmanager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: buildmanager
    namespace: default
