apiVersion: v1
kind: Service
metadata:
  name: buildmanager
  labels:
    app: buildmanager
    chart: {{ template "panux-builder.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: http
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: panux-builder-buildmanager
    release: {{ .Release.Name }}
