apiVersion: v1
kind: Service
metadata:
  name: pbuild
  labels:
    app: pbuild
    chart: {{ template "panux-builder.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001
      protocol: TCP
      name: http
  selector:
    app: panux-builder-pbuild
